### ISSUE TITLE
app starts on initial page, following link leaves page and doesn't hide video

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/webxr-ios#4]
Just built app (Sept 19), and when I click on one of the sample links on the first page, the white page does not go away, and the video is not shown.  The AR UI ("Add Anchor") shows, and objects (teapot, cubes) also show and move appropriately.

This is with iOS11 GM release on iPhone7plus, built with Xcode GM candidate.

**Comment by TrevorFSmith** [comment]
@blairmacintyre Can you still reproduce this? I can't on the code in master.

**Comment by blairmacintyre** [comment]
Nope, doesn't do that anymore.
